spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_sys
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    sql-show: true

server:
  port: 8081